export const CATEGORY_STYLE = {
        ReactJs: "#280004ff",
        NextJs: "darkblue",
        d3: "#464e47ff",
}

export const ALLPROJECTS = [
    {
        id: 1,
        title: "Quote Machine",
        img: "/portfolio/quotemachine.png",
        category: "ReactJs",
        github: "https://github.com/willian-pessoa/frases-engracadas",
        demo: "https://willian-pessoa.github.io/frases-engracadas/",
    },
    {
        id: 2,
        title: "Markdown Previewer",
        img: "/portfolio/markdown.png",
        category: "ReactJs",
        github: "https://github.com/willian-pessoa/markdown-previewer",
        demo: "https://willian-pessoa.github.io/markdown-previewer/",
    },
    {
        id: 3,
        title: "Drum Machine",
        img: "/portfolio/drum.png",
        category: "ReactJs",
        github: "https://github.com/willian-pessoa/drum-machine",
        demo: "https://willian-pessoa.github.io/drum-machine/",
    },
    {
        id: 4,
        title: "JavaScript Calculator",
        img: "/portfolio/calculator.png",
        category: "ReactJs",
        github: "https://github.com/willian-pessoa/javascript-calculator",
        demo: "https://willian-pessoa.github.io/javascript-calculator/",
    },
    {
        id: 5,
        title: "Pomodoro Clock",
        img: "/portfolio/pomodoro.png",
        category: "ReactJs",
        github: "https://github.com/willian-pessoa/pomodoro-clock",
        demo: "https://willian-pessoa.github.io/pomodoro-clock/",
    },
    {
        id: 6,
        title: "Letter Pairs Memory Trainer",
        img: "/portfolio/letterpair.png",
        category: "ReactJs",
        github: "https://github.com/willian-pessoa/letter-pairs-memo",
        demo: "https://willian-pessoa.github.io/letter-pairs-memo/",
    },
    {
        id: 7,
        title: "Bar Chart",
        img: "/portfolio/barchart.png",
        category: "d3",
        github: "https://github.com/willian-pessoa/bar-chart-gdp",
        demo: "https://willian-pessoa.github.io/bar-chart-gdp/",
    },
    {
        id: 8,
        title: "Tree Map",
        img: "/portfolio/treemap.png",
        category: "d3",
        github: "https://github.com/willian-pessoa/Treemap-Diagram",
        demo: "https://willian-pessoa.github.io/pomodoro-clock/",
    },
    {
        id: 9,
        title: "Choropleth Map",
        img: "/portfolio/choroplethmap.png",
        category: "d3",
        github: "https://github.com/willian-pessoa/Choropleth-Map",
        demo: "https://willian-pessoa.github.io/Choropleth-Map/",
    },
    {
        id: 10,
        title: "Heat Map",
        img: "/portfolio/heatmap.png",
        category: "d3",
        github: "https://github.com/willian-pessoa/heat-map",
        demo: "https://willian-pessoa.github.io/pomodoro-clock/",
    },
    {
        id: 11,
        title: "Real State",
        img: "/portfolio/realestate.png",
        category: "NextJs",
        github: "https://github.com/willian-pessoa/real-estate",
        demo: "https://real-estate-willian-pessoa.vercel.app/",
    },
    {
        id: 12,
        title: "First Portfolio App",
        img: "/portfolio/oldportfolio.png",
        category: "ReactJs",
        github: "https://github.com/willian-pessoa/Portfolio-App",
        demo: "https://willian-pessoa.github.io/Portfolio-App/",
    },
    {
        id: 13,
        title: "PokeNext",
        img: "/portfolio/pokenext.png",
        category: "NextJs",
        github: "https://github.com/willian-pessoa/pokenext",
        demo: "https://pokenext-xi.vercel.app/",
    },
    {
        id: 14,
        title: "BLD Trainer",
        img: "/portfolio/bldtrainer.png",
        category: "ReactJs",
        github: "https://github.com/willian-pessoa/bld-trainer",
        demo: "https://willian-pessoa.github.io/bld-trainer/",
    },
]